import {chromium,expect} from '@playwright/test'
import {mkdir,writeFile,readFile} from 'node:fs/promises'
import path from 'node:path'
const root=path.resolve('..');const out=path.join(root,'docs/screenshots');await mkdir(out,{recursive:true})
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium-browser',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--no-proxy-server']})
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));const checks=[]
try{
 await page.goto('http://127.0.0.1:8018',{waitUntil:'networkidle'});await expect(page.getByRole('heading',{name:'计算机视觉实验平台'})).toBeVisible();await page.screenshot({path:path.join(out,'home.png'),fullPage:true});checks.push('首页与真实示例素材加载')
 await page.getByRole('button',{name:'开始第一个实验'}).click();await expect(page.getByRole('heading',{name:/Canny/})).toBeVisible();await page.getByRole('button',{name:'运行实验',exact:true}).click();await expect(page.locator('.job-status.completed')).toBeVisible({timeout:30000});await expect(page.locator('.download-row a').filter({hasText:'全部结果 ZIP'})).toBeVisible();checks.push('Canny 示例 → 运行 → 展示 → ZIP 下载入口')
 await page.getByRole('button',{name:'滑动',exact:true}).click();await page.locator('input[aria-label="对比滑块"]').fill('30');await page.locator('input[aria-label="同步缩放"]').fill('1.8');await page.getByRole('button',{name:'Python 示例'}).click();await expect(page.locator('.code-panel pre')).toContainText('canny');await page.screenshot({path:path.join(out,'experiment.png'),fullPage:true});checks.push('滑动对比、同步缩放、当前参数 Python 示例')
 await page.getByRole('link',{name:'处理流水线',exact:true}).click();await page.locator('select[aria-label="流水线素材"]').selectOption('example-parts');await page.getByRole('button',{name:'运行流程'}).click();await expect(page.locator('.job-status.completed')).toBeVisible({timeout:30000});await expect(page.locator('.pipeline-results figure')).toHaveCount(6);checks.push('五步流水线和逐步结果')
 await page.goto('http://127.0.0.1:8018/#algorithm/instance');await page.locator('.asset-bar input[type=file]').setInputFiles({name:'bus.jpg',mimeType:'image/jpeg',buffer:await readFile(path.join(root,'assets/examples/bus.jpg'))});await expect(page.locator('.asset-bar .muted')).toContainText('bus.jpg');await page.getByRole('button',{name:'运行实验',exact:true}).click();await expect(page.locator('.job-status.completed')).toBeVisible({timeout:60000});await expect(page.locator('.viewer-footer')).toContainText('掩膜');const layer=page.locator('.viewer-footer label').filter({hasText:'掩膜'}).locator('input');await layer.uncheck();await expect(layer).not.toBeChecked();await layer.check();checks.push('上传真实照片、本地实例分割、独立掩膜图层开关')
 await page.goto('http://127.0.0.1:8018/#algorithm/frame_diff');await page.locator('.asset-bar input[type=file]').setInputFiles({name:'pedestrians.mp4',mimeType:'video/mp4',buffer:await readFile(path.join(root,'assets/examples/pedestrians.mp4'))});await expect(page.locator('.asset-bar .muted')).toContainText('pedestrians.mp4',{timeout:30000});await page.getByRole('button',{name:'运行实验',exact:true}).click();await expect(page.locator('.job-status.completed')).toBeVisible({timeout:60000});await expect(page.locator('video')).toHaveCount(2);await page.waitForFunction(()=>Array.from(document.querySelectorAll('video')).every(v=>v.readyState>=2));await page.locator('input[aria-label="视频时间轴"]').fill('1.5');await page.locator('.video-controls>button').first().click();await page.waitForTimeout(900);const videoTimes=await page.locator('video').evaluateAll(videos=>videos.map(v=>({time:v.currentTime,duration:v.duration,error:v.error?.message})));if(videoTimes.some(v=>v.time<1.6||v.error))throw new Error(JSON.stringify(videoTimes));if(Math.abs(videoTimes[0].duration-videoTimes[1].duration)>.15)throw new Error('视频时长不一致');await page.locator('.video-controls>button').first().click();await page.screenshot({path:path.join(out,'video.png'),fullPage:true});checks.push('原视频与 H.264 结果播放、定位、同步时长')
 await page.goto('http://127.0.0.1:8018/#models');await expect(page.getByRole('heading',{name:'本地模型管理'})).toBeVisible();await expect(page.locator('.model-card')).toHaveCount(22);checks.push('22 个模型管理条目与文件状态')
 await page.goto('http://127.0.0.1:8018/#history');await expect(page.locator('.history-list article').first()).toBeVisible();checks.push('SQLite 实验历史')
 await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:8018/#home');await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});const horizontal=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);if(horizontal)throw new Error('移动端存在横向溢出');checks.push('移动端布局无横向溢出')
 if(errors.length)throw new Error(errors.join('\n'))
 await writeFile(path.join(root,'docs/browser-validation.json'),JSON.stringify({status:'passed',checks,console_errors:errors},null,2));console.log(JSON.stringify({status:'passed',checks},null,2))
}finally{await browser.close()}
