import {chromium,expect} from '@playwright/test'
import {writeFile} from 'node:fs/promises'
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium-browser',headless:true,args:['--no-sandbox','--no-proxy-server']})
const page=await browser.newPage({viewport:{width:1440,height:1000}}),checks=[],errors=[],created=[]
page.on('pageerror',e=>errors.push(e.message));page.on('response',async r=>{if(r.request().method()==='POST'&&r.url().endsWith('/api/experiments')&&r.ok())created.push((await r.json()).id)})
try{
 await page.goto('http://127.0.0.1:8018/#algorithm/text_retrieval',{waitUntil:'networkidle'});await page.getByRole('button',{name:'载入完整示例'}).click();await page.getByRole('button',{name:'运行实验',exact:true}).click();await expect(page.locator('.job-status.completed')).toBeVisible({timeout:60000});await expect(page.locator('.retrieval-results img')).toHaveCount(3);await expect(page.locator('.retrieval-results figure').first()).toContainText('街景公交');checks.push('CLIP 文本查询返回真实图库排序与图片')
 await page.goto('http://127.0.0.1:8018/#pipeline');await page.getByLabel('流水线素材').selectOption('example-parts');await page.getByRole('button',{name:'运行流程'}).click();await expect(page.locator('.pipeline-results figure')).toHaveCount(6,{timeout:30000});await page.goto('http://127.0.0.1:8018/#history');const pipeline=page.locator('.history-list article').filter({has:page.getByRole('heading',{name:'pipeline',exact:true})}).first();await pipeline.getByRole('button',{name:'打开实验'}).click();await expect(page.getByLabel('流水线素材')).toHaveValue('example-parts');await expect(page.locator('.pipeline-results figure')).toHaveCount(6);checks.push('实验历史恢复流水线输入、步骤与逐步结果')
 await page.goto('http://127.0.0.1:8018/#algorithm/events');await page.getByRole('button',{name:'载入完整示例'}).click();await page.getByRole('button',{name:'运行实验',exact:true}).click();await expect(page.locator('.job-status.completed')).toBeVisible({timeout:60000});await expect(page.locator('.event-strip button').first()).toBeVisible();await page.locator('.event-strip button').first().click();await expect(page.locator('.event-strip img').first()).toBeVisible();checks.push('真实检测事件时间轴、触发缩略图与跳转')
 if(errors.length)throw new Error(errors.join('\n'));await writeFile('../docs/browser-final.json',JSON.stringify({status:'passed',checks,console_errors:errors},null,2));console.log(JSON.stringify({status:'passed',checks},null,2))
}finally{await writeFile('../data/browser-final-artifacts.json',JSON.stringify(created));await browser.close()}
