import {useCallback,useEffect,useMemo,useState} from 'react'
import {Search,ChevronDown,ChevronRight,House,FlaskConical,Workflow,Database,History,PanelLeftClose,PanelLeftOpen,BookOpen,Command,ArrowUpRight} from 'lucide-react'
import {api,errorMessage} from './api'
import type {Algorithm,Asset,Job,Model} from './types'
import {Home,ModelsPage,HistoryPage,PipelinePage} from './Pages'
import {Experiment} from './Experiment'

export default function App(){
  const [route,setRoute]=useState(location.hash.slice(1)||'home');const [algorithms,setAlgorithms]=useState<Algorithm[]>([]),[assets,setAssets]=useState<Asset[]>([]),[models,setModels]=useState<Model[]>([]);const [asset,setAsset]=useState<Asset|null>(null);const [search,setSearch]=useState('');const [open,setOpen]=useState<string[]>(['图像基础']);const [error,setError]=useState('');const [collapsed,setCollapsed]=useState(false);const [initialJob,setInitialJob]=useState<Job>();const [device,setDevice]=useState('cpu')
  const refreshAssets=useCallback(()=>{void api<Asset[]>('/assets').then(setAssets).catch(e=>setError(errorMessage(e)))},[]);const refreshModels=useCallback(()=>{void api<Model[]>('/models').then(setModels).catch(e=>setError(errorMessage(e)))},[])
  useEffect(()=>{const listener=()=>{setRoute(location.hash.slice(1)||'home');window.scrollTo(0,0)};window.addEventListener('hashchange',listener);void api<Algorithm[]>('/algorithms').then(setAlgorithms).catch(e=>setError(errorMessage(e)));void api<{device:string}>('/health').then(x=>setDevice(x.device)).catch(()=>{});refreshAssets();refreshModels();return()=>window.removeEventListener('hashchange',listener)},[])
  const selected=algorithms.find(a=>route==='algorithm/'+a.id);const categories=useMemo(()=>[...new Set(algorithms.map(a=>a.category))],[algorithms]);const results=algorithms.filter(a=>[a.name,a.english,a.uses,a.summary,a.id].join(' ').toLowerCase().includes(search.toLowerCase()));
  useEffect(()=>{if(selected&&!open.includes(selected.category))setOpen(old=>[...old,selected.category])},[selected?.id])
  function navigate(id:string,nextAsset?:Asset){setInitialJob(undefined);if(nextAsset)setAsset(nextAsset);location.hash='algorithm/'+id}
  async function openJob(job:Job){try{const all=await api<Asset[]>('/assets');setAssets(all);const found=all.find(a=>a.id===job.asset_id);if(found)setAsset(found);setInitialJob(job);location.hash=job.algorithm==='pipeline'?'pipeline':'algorithm/'+job.algorithm}catch(e){setError(errorMessage(e))}}
  const ready=models.filter(m=>m.state==='ready').length
  return <div className={'app-shell '+(collapsed?'sidebar-collapsed':'')}><aside className="sidebar"><a className="brand" href="#home"><span className="brand-mark"><span/><span/><span/><span/></span><div><strong>计算机视觉实验平台</strong></div></a><nav className="primary-nav">{[['home','学习概览',House],['pipeline','处理流水线',Workflow],['models','模型管理',Database],['history','实验记录',History]].map(([id,label,Icon])=>{const I=Icon as typeof House;return <a key={String(id)} href={'#'+id} className={route===id?'active':''}><I size={18}/><span>{String(label)}</span>{id==='models'&&<em>{ready}</em>}</a>})}</nav><div className="sidebar-divider"/><div className="sidebar-section-label">算法目录 <span>{algorithms.length}</span></div><div className="search-box"><Search size={16}/><input aria-label="搜索算法" placeholder="搜索算法、英文名或用途…" value={search} onChange={e=>setSearch(e.target.value)}/><kbd>⌕</kbd></div><nav className="algorithm-nav">{categories.map((category,i)=>{const items=results.filter(a=>a.category===category);if(!items.length)return null;const expanded=!!search||open.includes(category);return <div className="category" key={category}><button className={selected?.category===category?'current':''} onClick={()=>setOpen(expanded?open.filter(x=>x!==category):[...open,category])}><span className="category-index">{String(i+1).padStart(2,'0')}</span><span>{category}</span><em>{items.length}</em>{expanded?<ChevronDown size={13}/>:<ChevronRight size={13}/>}</button>{expanded&&<div className="algorithm-children">{items.map(a=><a href={'#algorithm/'+a.id} key={a.id} onClick={()=>setInitialJob(undefined)} className={selected?.id===a.id?'active':''}><i/>{a.name}{a.model&&<span className="tiny-ai">AI</span>}</a>)}</div>}</div>})}{!results.length&&<p className="muted">没有匹配的算法</p>}</nav><div className="sidebar-bottom"><span className="local-dot"/><div><strong>本地实验环境</strong><small>{device.toUpperCase()} · 数据保存在本机</small></div><ArrowUpRight size={15}/></div></aside>
    <div className="main-shell"><header className="topbar"><div><button className="icon-button" aria-label="切换侧栏" onClick={()=>setCollapsed(!collapsed)}>{collapsed?<PanelLeftOpen size={19}/>:<PanelLeftClose size={19}/>}</button><span className="topbar-separator"/><span>工作空间</span><ChevronRight size={13}/><strong>{selected?selected.category:({home:'学习概览',pipeline:'处理流水线',models:'模型管理',history:'实验记录'}[route]||'学习概览')}</strong></div><div><span className="environment-badge"><span/>{device.toUpperCase()}</span><a href="/docs" target="_blank" rel="noreferrer"><BookOpen size={15}/>API 文档</a></div></header><main className={'page '+(route==='home'?'home-page':'')}>
      {error&&<div className="error-banner" role="alert">{error}<button onClick={()=>{setError('');refreshAssets();refreshModels();void api<Algorithm[]>('/algorithms').then(setAlgorithms)}}>重试连接</button></div>}
      {!algorithms.length&&!error?<div className="loading-page"><FlaskConical size={36}/><p>正在连接视觉实验服务…</p></div>:selected?<Experiment key={selected.id+'-'+(initialJob?.id||'new')} algorithm={selected} asset={asset} setAsset={setAsset} assets={assets} refreshAssets={refreshAssets} models={models} onFrame={frame=>{refreshAssets();navigate('gray',frame)}} initialJob={initialJob}/>:route==='models'?<ModelsPage models={models} refresh={refreshModels}/>:route==='history'?<HistoryPage algorithms={algorithms} onOpen={job=>void openJob(job)}/>:route==='pipeline'?<PipelinePage key={initialJob?.algorithm==='pipeline'?initialJob.id:'new'} algorithms={algorithms} assets={assets} refreshAssets={refreshAssets} initialJob={initialJob?.algorithm==='pipeline'?initialJob:undefined}/>:<Home algorithms={algorithms} assets={assets} models={models} onSelect={navigate}/>}
    </main></div></div>
}
