import {useEffect,useRef,useState,type PointerEvent as ReactPointerEvent} from 'react'
import {Columns2,SplitSquareHorizontal,Image as ImageIcon,Move,Square,MousePointer2,Paintbrush,Undo2,ZoomIn,Play,Pause,Camera,RotateCcw} from 'lucide-react'
import type {Asset,JobResult} from './types'
import {api,errorMessage} from './api'

export function ImageViewer({asset,result,params,onParams,interaction,previewUrl}:{asset:Asset;result?:JobResult;params:Record<string,unknown>;onParams:(p:Record<string,unknown>)=>void;interaction:string;previewUrl?:string}){
  const [mode,setMode]=useState('side');const [zoom,setZoom]=useState(1);const [pan,setPan]=useState([0,0]);const [split,setSplit]=useState(50);const [tool,setTool]=useState('pan');const [hidden,setHidden]=useState<string[]>([]);const [pointLabel,setPointLabel]=useState(1);const [brush,setBrush]=useState(15);const [cursor,setCursor]=useState<[number,number]|null>(null);const [loupe,setLoupe]=useState(false);const start=useRef<{x:number;y:number;clientX:number;clientY:number;pan:number[]}|null>(null);const inputSvg=useRef<SVGSVGElement>(null)
  const width=Number(asset.metadata.width||640),height=Number(asset.metadata.height||480);const src=asset.kind==='video'?asset.poster!:asset.url;const target=previewUrl||result?.image_url||src;const rw=result?.width||width,rh=result?.height||height;const layers=previewUrl?[]:result?.layers||[];const matchingSize=width===rw&&height===rh
  useEffect(()=>{setZoom(1);setPan([0,0]);setHidden([]);setCursor(null)},[asset.id])
  useEffect(()=>{setTool(interaction==='rectangle'?'rectangle':interaction==='polygon'?'polygon':interaction==='brush'?'brush':interaction==='points'||interaction==='prompts'?'point':'pan')},[interaction])
  useEffect(()=>{if(!matchingSize&&mode==='slide')setMode('side')},[matchingSize,mode])
  function coordinates(e:ReactPointerEvent<SVGSVGElement>){const svg=e.currentTarget,point=svg.createSVGPoint();point.x=e.clientX;point.y=e.clientY;const matrix=svg.getScreenCTM();if(!matrix)return [0,0];const p=point.matrixTransform(matrix.inverse());return [Math.round(Math.max(0,Math.min(width-1,p.x))),Math.round(Math.max(0,Math.min(height-1,p.y)))]}
  function down(e:ReactPointerEvent<SVGSVGElement>){e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);const [x,y]=coordinates(e);start.current={x,y,clientX:e.clientX,clientY:e.clientY,pan:[...pan]};
    if(tool==='point')onParams({...params,points:[...(params.points as number[][]||[]),[x,y,e.button===2?0:pointLabel]]});
    if(tool==='polygon')onParams({...params,polygon:[...(params.polygon as number[][]||[]),[x,y]]});
    if(tool==='brush')onParams({...params,mask_points:[...(params.mask_points as number[][]||[]),[x,y,brush]]})
  }
  function move(e:ReactPointerEvent<SVGSVGElement>){const [x,y]=coordinates(e);setCursor([x,y]);const s=start.current;if(!s)return;
    if(tool==='pan')setPan([s.pan[0]+e.clientX-s.clientX,s.pan[1]+e.clientY-s.clientY]);
    if(tool==='rectangle')onParams({...params,roi:[Math.min(s.x,x),Math.min(s.y,y),Math.abs(x-s.x),Math.abs(y-s.y)]});
    if(tool==='brush')onParams({...params,mask_points:[...(params.mask_points as number[][]||[]),[x,y,brush]]})
  }
  const roi=params.roi as number[]|undefined,points=params.points as number[][]||[],polygon=params.polygon as number[][]||[],mask=params.mask_points as number[][]||[];
  const interactionShapes=<>{roi&&<rect x={roi[0]} y={roi[1]} width={roi[2]} height={roi[3]} fill="#16b8a822" stroke="#36e3c4" strokeWidth={2/zoom}/>}<polyline points={polygon.map(p=>p.join(',')).join(' ')} fill={polygon.length>2?'#d9a44122':'none'} stroke="#ffd166" strokeWidth={2/zoom}/>{polygon.map(([x,y],i)=><circle key={i} cx={x} cy={y} r={4/zoom} fill="#ffd166"/>)}{points.map(([x,y,label],i)=><g key={i}><circle cx={x} cy={y} r={5/zoom} fill={label?'#48e5ab':'#ff6c85'} stroke="white" strokeWidth={1/zoom}/><text x={x+8/zoom} y={y+4/zoom} fontSize={12/zoom} fill="white">{label?'+':'−'}</text></g>)}{mask.map(([x,y,r],i)=><circle key={i} cx={x} cy={y} r={r} fill="#ee617baa"/>)}</>
  function pane(output:boolean,slide=false){const vw=output&&!slide?rw:width,vh=output&&!slide?rh:height;return <div className="image-pane"><span className="image-label">{slide?'滑动对比':output?'处理结果':'原始输入'} {output&&previewUrl&&<em>低分辨率预览</em>}</span><div className="image-viewport"><svg ref={!output?inputSvg:undefined} viewBox={`0 0 ${vw} ${vh}`} style={{transform:`translate(${pan[0]}px,${pan[1]}px) scale(${zoom})`,cursor:tool==='pan'?'grab':'crosshair'}} onPointerDown={!output||slide?down:undefined} onPointerMove={!output||slide?move:undefined} onPointerUp={()=>{start.current=null}} onPointerCancel={()=>{start.current=null}} onContextMenu={e=>e.preventDefault()}>
      <image href={output&&!slide?target:src} width={vw} height={vh}/>
      {slide?<><defs><clipPath id="compare-clip"><rect width={width*split/100} height={height}/></clipPath></defs><g clipPath="url(#compare-clip)"><image href={target} width={width} height={height}/>{layers.filter(l=>!hidden.includes(l.name)).map(l=><image key={l.name} href={l.url} width={width} height={height}/>)}</g><line x1={width*split/100} x2={width*split/100} y2={height} stroke="white" strokeWidth={2/zoom}/>{interactionShapes}</>:output?layers.filter(l=>!hidden.includes(l.name)).map(l=><image key={l.name} href={l.url} width={vw} height={vh}/>):interactionShapes}
    </svg></div>{!output&&cursor&&<span className="coordinate">x {cursor[0]} · y {cursor[1]} px</span>}</div>}
  return <div className="viewer"><div className="viewer-tools"><div className="segmented">{[['side',Columns2,'并排'],['slide',SplitSquareHorizontal,'滑动'],['result',ImageIcon,'结果']].map(([key,Icon,label])=>{const I=Icon as typeof Columns2;return <button key={String(key)} title={String(label)} className={mode===key?'active':''} disabled={key==='slide'&&!matchingSize} onClick={()=>setMode(String(key))}><I size={15}/>{String(label)}</button>})}</div><div className="zoom"><ZoomIn size={14}/><input aria-label="同步缩放" type="range" min="0.5" max="4" step="0.1" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/><span>{Math.round(zoom*100)}%</span><button title="重置视图" className="icon-button" onClick={()=>{setZoom(1);setPan([0,0])}}><RotateCcw size={14}/></button></div></div>
    {interaction&&<div className="draw-tools"><span>原图交互</span><button className={tool==='pan'?'active':''} onClick={()=>setTool('pan')}><Move size={14}/>平移</button>{['rectangle','prompts'].includes(interaction)&&<button className={tool==='rectangle'?'active':''} onClick={()=>setTool('rectangle')}><Square size={14}/>矩形 ROI</button>}{['points','prompts'].includes(interaction)&&<><button className={tool==='point'?'active':''} onClick={()=>setTool('point')}><MousePointer2 size={14}/>点选</button>{interaction==='prompts'&&<select aria-label="点类型" value={pointLabel} onChange={e=>setPointLabel(Number(e.target.value))}><option value={1}>前景 +</option><option value={0}>背景 −</option></select>}</>}{interaction==='polygon'&&<button className={tool==='polygon'?'active':''} onClick={()=>setTool('polygon')}><MousePointer2 size={14}/>依次选点</button>}{interaction==='brush'&&<><button onClick={()=>setTool('brush')}><Paintbrush size={14}/>画笔</button><input aria-label="画笔半径" type="range" min={2} max={60} value={brush} onChange={e=>setBrush(Number(e.target.value))}/></>}<button onClick={()=>{const next={...params};for(const key of ['roi','points','polygon','mask_points'])delete next[key];onParams(next)}}><Undo2 size={14}/>清空</button></div>}
    <div className={'image-grid '+(mode!=='side'?'single':'')}>{mode==='side'?<>{pane(false)}{pane(true)}</>:pane(true,mode==='slide')}</div>
    {mode==='slide'&&<input className="split-range" aria-label="对比滑块" type="range" min={0} max={100} value={split} onChange={e=>setSplit(Number(e.target.value))}/>}
    <div className="viewer-footer"><span>{width} × {height} px · 原图坐标</span><label><input type="checkbox" checked={loupe} onChange={e=>setLoupe(e.target.checked)}/>局部放大</label>{layers.map(layer=><label key={layer.name}><input type="checkbox" checked={!hidden.includes(layer.name)} onChange={()=>setHidden(hidden.includes(layer.name)?hidden.filter(x=>x!==layer.name):[...hidden,layer.name])}/>{layer.name}</label>)}</div>
    {loupe&&cursor&&<div className="loupe"><svg viewBox={`${cursor[0]-40} ${cursor[1]-40} 80 80`}><image href={src} width={width} height={height}/></svg><span>原图局部 · 2×</span></div>}
  </div>
}

export function VideoViewer({asset,result,onFrame}:{asset:Asset;result?:JobResult;onFrame:(asset:Asset)=>void}){
  const left=useRef<HTMLVideoElement>(null),right=useRef<HTMLVideoElement>(null);const [time,setTime]=useState(0),[duration,setDuration]=useState(Number(asset.metadata.duration||0)),[playing,setPlaying]=useState(false),[error,setError]=useState('');
  useEffect(()=>{setPlaying(false);setTime(0)},[asset.id])
  function seek(t:number){setTime(t);if(left.current)left.current.currentTime=t;if(right.current)right.current.currentTime=t}
  async function play(){try{if(playing){left.current?.pause();right.current?.pause();setPlaying(false)}else{await left.current?.play();if(right.current){right.current.currentTime=left.current?.currentTime||0;await right.current.play()}setPlaying(true)}}catch(e){setError(errorMessage(e))}}
  async function snapshot(){try{const video=right.current||left.current;if(!video)return;const canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d')!.drawImage(video,0,0);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)return;const form=new FormData();form.append('file',blob,`frame-${time.toFixed(2)}.png`);onFrame(await api<Asset>('/assets',form))}catch(e){setError(errorMessage(e))}}
  return <div className="video-viewer"><div className="video-grid"><div><span>原始视频</span><video ref={left} src={asset.url} playsInline onLoadedMetadata={()=>setDuration(left.current?.duration||0)} onTimeUpdate={()=>{const t=left.current?.currentTime||0;setTime(t);if(right.current&&Math.abs(right.current.currentTime-t)>.15)right.current.currentTime=t}} onEnded={()=>{setPlaying(false);right.current?.pause()}} onError={()=>setError('原视频播放失败，请检查视频编码与文件是否完整')}/></div><div><span>处理结果</span>{result?.video_url?<video ref={right} src={result.video_url} playsInline muted onError={()=>setError('结果视频播放失败')}/>:<div className="video-empty"><Play size={34}/><p>运行后在这里查看处理结果</p></div>}</div></div><div className="video-controls"><button onClick={()=>void play()}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><input aria-label="视频时间轴" type="range" min={0} max={duration||1} step={.01} value={time} onChange={e=>seek(Number(e.target.value))}/><input aria-label="定位秒数" type="number" min={0} max={duration} step={.1} value={time.toFixed(2)} onChange={e=>seek(Math.max(0,Math.min(duration,Number(e.target.value))))}/><span>/ {duration.toFixed(2)}s</span><button onClick={()=>void snapshot()}><Camera size={15}/>单帧实验</button></div>{error&&<p className="danger">{error}</p>}{result?.sampling&&<p className="muted small">{result.sampling} · {result.frame_count} 帧 · {result.fps?.toFixed(2)} fps</p>}{!!result?.events?.length&&<div className="event-strip">{result.events.map((event,i)=><button key={i} onClick={()=>seek(event.time)} title={JSON.stringify(event.evidence||event.top5)}>{event.frame_url&&<img src={event.frame_url} alt="事件触发帧"/>}<strong>{event.kind}</strong><span>{event.time.toFixed(2)} 秒 {event.track_id&&`· #${event.track_id}`}</span></button>)}</div>}</div>
}

export function CloudViewer({points}:{points:number[][]}){
  const canvas=useRef<HTMLCanvasElement>(null);const [rotation,setRotation]=useState([.3,.4]);const [scale,setScale]=useState(1);const last=useRef<number[]|null>(null)
  useEffect(()=>{const ctx=canvas.current?.getContext('2d');if(!ctx||!points.length)return;const width=800,height=440;ctx.fillStyle='#101e2a';ctx.fillRect(0,0,width,height);const center=[0,1,2].map(i=>points.reduce((n,p)=>n+p[i],0)/points.length);const radius=Math.max(...points.map(p=>Math.hypot(p[0]-center[0],p[1]-center[1],p[2]-center[2])))||1;const [yaw,pitch]=rotation;for(const p of points){const x=p[0]-center[0],y=p[1]-center[1],z=p[2]-center[2];const rx=x*Math.cos(yaw)-z*Math.sin(yaw),rz=x*Math.sin(yaw)+z*Math.cos(yaw),ry=y*Math.cos(pitch)-rz*Math.sin(pitch);ctx.fillStyle=`hsl(${160+z/radius*80} 65% 65%)`;ctx.fillRect(width/2+rx/radius*190*scale,height/2-ry/radius*190*scale,2,2)}},[points,rotation,scale])
  return <div className="cloud-viewer"><canvas ref={canvas} width={800} height={440} onPointerDown={e=>{last.current=[e.clientX,e.clientY];e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(last.current){setRotation([rotation[0]+(e.clientX-last.current[0])*.01,rotation[1]+(e.clientY-last.current[1])*.01]);last.current=[e.clientX,e.clientY]}}} onPointerUp={()=>{last.current=null}}/><div><span>拖动旋转 · {points.length.toLocaleString()} 个显示点</span><input aria-label="点云缩放" type="range" min={.2} max={3} step={.1} value={scale} onChange={e=>setScale(Number(e.target.value))}/></div></div>
}
